# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'pathname'

# Box / OS
VAGRANT_BOX = 'centos/7'
VAGRANT_BOX_VERSION = '1905.1'

# Memorable name for your
VM_NAME = 'test-chef-server'

# VM User — 'vagrant' by default
VM_USER = 'vagrant'

# Username on your OS
USERNAME = "#{ENV['USERNAME'] || `whoami`}"

# Host folder to sync (Assumes repo in dir named GitHub)
HOST_PATH = Pathname.new(Dir.pwd).parent.to_s

# Where to sync to on Guest — 'vagrant' is the default user name
GUEST_PATH = "/home/" + VM_USER + "/" + File.basename(HOST_PATH)

Vagrant.configure(2) do |config|
  # Vagrant box from Hashicorp
  config.vagrant.plugins = "vagrant-vbguest"
  config.vm.box = VAGRANT_BOX
  config.vm.box_version = VAGRANT_BOX_VERSION

  # Actual machine name
  config.vm.hostname = VM_NAME

  #Setup Network Details
  config.vm.network "private_network", ip: "172.28.128.19"
  #config.vm.network "forwarded_port", guest: 80, host:8080

  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 1024
  end

  # Sync folder
  config.vm.synced_folder HOST_PATH, GUEST_PATH

  # Install Git, Node.js 12.x.x, Latest npm
  config.vm.provision "shell", inline: <<-SHELL
    yum update
    yum install -y git
    sudo rpm -Uvh https://packages.chef.io/files/stable/chef-server/13.0.17/el/7/chef-server-core-13.0.17-1.el7.x86_64.rpm
  SHELL
end
